query($categoryId: ID!) {
  category(id: $categoryId) {
    name
    id
    products {
      description
      name
    }
  }
}

query($productId: ID!) {
  product(id: $productId) {
    name
    id
    description
    price
    category {
      name
      id
    }
  }
}

query {
  categories {
    name
    id
    products(filter: { onSale: true, avgRating: 4 }) {
      description
      onSale
      name
      reviews {
        rating
      }
    }
  }
}